# Generated by Django 3.2 on 2021-05-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_commune', models.FileField(null=True, upload_to='media/')),
                ('rec_location', models.FileField(null=True, upload_to='media/')),
                ('rec_name', models.FileField(null=True, upload_to='media/')),
                ('cercle_num', models.CharField(choices=[('Sikasso', 'Sikasso'), ('Koutiala', 'Koutiala'), ('Bougouni', 'Bougouni'), ('Kadiolo', 'Kadiolo'), ('Kolondiéba', 'Kolondiéba'), ('Yanfolila', 'Yanfolila'), ('Yorosso', 'Yorosso')], max_length=30, null=True)),
                ('tree_num', models.CharField(choices=[('Pterocarpus erinaceus', 'Pterocarpus erinaceus'), ('Terminalia habeensis', 'Terminalia habeensis'), ('Afzelia Africana', 'Afzelia Africana'), ('Khaya senegalensis', 'Khaya senegalensis'), ('Dalbergia melanoxylon', 'Dalbergia melanoxylon'), ('Unknown', 'Unknown')], max_length=30, null=True)),
                ('tree_count', models.IntegerField()),
                ('chosen_language', models.CharField(choices=[('en', 'english'), ('br', 'bambara'), ('fr', 'france')], max_length=30, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='treeaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cercle', models.CharField(max_length=100)),
                ('tree', models.CharField(max_length=100)),
                ('tree_count', models.IntegerField()),
                ('phone_number', models.CharField(max_length=30)),
            ],
        ),
    ]
