# Generated by Django 3.2 on 2021-04-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICT4D_prototype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='voice',
            field=models.FileField(default=0, upload_to='voicexml/'),
            preserve_default=False,
        ),
    ]
