# Generated by Django 3.2 on 2021-04-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICT4D_prototype', '0002_person_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='treeaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cercle', models.CharField(max_length=100)),
                ('tree', models.CharField(max_length=100)),
                ('tree_count', models.IntegerField()),
            ],
        ),
    ]
