# Generated by Django 3.2 on 2021-04-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICT4D_prototype', '0003_treeaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeaid',
            name='phone_number',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
