# Generated by Django 3.2 on 2021-05-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICT4D_prototype', '0006_auto_20210506_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
