# Generated by Django 3.2 on 2021-05-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICT4D_prototype', '0007_document_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='cercle_num',
        ),
        migrations.RemoveField(
            model_name='document',
            name='chosen_language',
        ),
        migrations.RemoveField(
            model_name='document',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='document',
            name='rec_commune',
        ),
        migrations.RemoveField(
            model_name='document',
            name='rec_location',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tree_count',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tree_num',
        ),
    ]
