# Generated by Django 3.2 on 2021-05-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICT4D_prototype', '0008_auto_20210506_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='rec_commune',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='document',
            name='rec_location',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='document',
            name='tree_num',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='rec_name',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
