# Generated by Django 3.2 on 2021-05-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICT4D_prototype', '0009_auto_20210509_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cercle_num',
            field=models.CharField(choices=[('Sikasso', 'Sikasso'), ('Koutiala', 'Koutiala'), ('Bougouni', 'Bougouni'), ('Kadiolo', 'Kadiolo'), ('Kolondiéba', 'Kolondiéba'), ('Yanfolila', 'Yanfolila'), ('Yorosso', 'Yorosso')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='chosen_language',
            field=models.CharField(choices=[('en', 'english'), ('br', 'bambara'), ('fr', 'france')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='tree_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='tree_num',
            field=models.CharField(choices=[('Pterocarpus erinaceus', 'Pterocarpus erinaceus'), ('Terminalia habeensis', 'Terminalia habeensis'), ('Afzelia Africana', 'Afzelia Africana'), ('Khaya senegalensis', 'Khaya senegalensis'), ('Dalbergia melanoxylon', 'Dalbergia melanoxylon'), ('Unknown', 'Unknown')], max_length=30, null=True),
        ),
    ]
