# Generated by Django 3.2 on 2021-05-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICT4D_prototype', '0010_auto_20210511_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeaid',
            name='dummy_rec',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
