# Generated by Django 3.2 on 2021-05-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICT4D_prototype', '0011_treeaid_dummy_rec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeaid',
            name='dummy_rec',
        ),
    ]
